version: '3'

services:
  postgresql:
    image: 'postgres:11.1'
    volumes:
      - './postgresql/data:/var/lib/postgresql/data'
  pg_admin:
    image: 'dpage/pgadmin4'
    ports:
      - 2080:80
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@localhost'
      PGADMIN_DEFAULT_PASSWORD: '0000'
    volumes:
      - './pgadmin:/var/lib/pgadmin'
